test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    
    exclude = ["install.subdir"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.787885e7.name = "Upgrade from 1.5.4"